spring.application.name: activity-planning-service

server:
  port: 8084

activity-planning-service:
  azure:
    api-endpoint: ${AZURE_OPENAI_ENDPOINT}
    api-key: ${AZURE_OPENAI_API_KEY}
    deployment-name: ${DEPLOYMENT_NAME}
